apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: imager-secretstore
  namespace: imager
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/imager-secrets.json
    - name: nestedSeparator
      value: ":"
