Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
AllowedHosts: "*"
Dapr:
  DaprPort: 3500
TempImages:
  PresignTTL: 1m
Serilog:
  MinimumLevel: "Information"
  Enrich: ["FromLogContext"]
  WriteTo:
    - Name: "Console"
    - Name: "File"
      Args:
        path: "log.log"
        fileSizeLimitBytes: 10000000
